import { Character, GlooWallSkin, OGBundle, Weapon, WeaponSkin } from '../types/game';

export const OG_BUNDLES: OGBundle[] = [
  {
    id: 'BUNDLE_S1_SAKURA',
    name: 'Sakura Blossom (Season 1)',
    season: 'SEASON 1 ELITE PASS',
    rarity: 'MYTHIC',
    color: '#EC4899',
    glowColor: '#F472B6',
    icon: '🌸',
    description: 'The legendary #1 Season 1 Elite Pass bundle. Pink cherry blossom mask & kimono suit.',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'BUNDLE_S2_HIPHOP',
    name: 'Hip-Hop OG (Season 2)',
    season: 'SEASON 2 ELITE PASS',
    rarity: 'MYTHIC',
    color: '#F59E0B',
    glowColor: '#FBBF24',
    icon: '🧢',
    description: 'The ultimate Season 2 Hip-Hop streetwear bundle with backwards cap and skull bandana.',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'BUNDLE_BREAKDANCER',
    name: 'Breakdancer / Street Boy',
    season: 'SEASON 3 OG',
    rarity: 'LEGENDARY',
    color: '#EF4444',
    glowColor: '#F87171',
    icon: '👟',
    description: 'Iconic red cap & black street outfit from Gold Royale. Pure OG nostalgia.',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'BUNDLE_NIGHT_CLOWN',
    name: 'Night Clown (Joker OG)',
    season: 'MAGIC CUBE OG',
    rarity: 'LEGENDARY',
    color: '#8B5CF6',
    glowColor: '#A78BFA',
    icon: '🤡',
    description: 'The creepy neon joker clown outfit. One of the most feared Magic Cube bundles.',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'BUNDLE_GREEN_CRIMINAL',
    name: 'Green Criminal Suit',
    season: 'TOP CRIMINAL OG',
    rarity: 'MYTHIC',
    color: '#10B981',
    glowColor: '#34D399',
    icon: '👺',
    description: 'The world famous Green Criminal heist jumpsuit with mask. Rare status symbol!',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'BUNDLE_BUNNY_WARRIOR',
    name: 'Bunny Warrior OG',
    season: 'EASTER OG',
    rarity: 'LEGENDARY',
    color: '#06B6D4',
    glowColor: '#38BDF8',
    icon: '🐰',
    description: 'Fierce bunny mask and armored tactical vest. Classic OG flex!',
    unlocked: false,
    cost: 3000,
  },
  {
    id: 'BUNDLE_ARCTIC_BLUE',
    name: 'Arctic Blue Frost',
    season: 'DIAMOND ROYALE',
    rarity: 'LEGENDARY',
    color: '#3B82F6',
    glowColor: '#60A5FA',
    icon: '❄️',
    description: 'Glowing electric ice-ninja armor with blue energy particle effects.',
    unlocked: false,
    cost: 3500,
  },
  {
    id: 'BUNDLE_COBRA_RAGE',
    name: 'Cobra Rage Evolving',
    season: 'MYTHIC COBRA',
    rarity: 'MYTHIC',
    color: '#DC2626',
    glowColor: '#F87171',
    icon: '🐍',
    description: 'Evolving crimson cobra battle suit with dynamic aura and specialized emotes.',
    unlocked: false,
    cost: 5000,
  },
];

export const CHARACTERS: Character[] = [
  {
    id: 'ALOK',
    name: 'DJ ALOK',
    title: 'Drop The Beat',
    skillName: 'Drop The Beat',
    skillType: 'ACTIVE',
    description: 'Creates a 5m aura that increases movement speed by 15% and restores 5 HP/sec for 10s.',
    cooldown: 45,
    avatarBg: 'from-amber-600 to-yellow-500',
    color: '#EAB308',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'KELLY',
    name: 'KELLY',
    title: 'Dash Specialist',
    skillName: 'Dash',
    skillType: 'PASSIVE',
    description: 'Sprinting speed increased by 15%. Always ready to outrun the shrinking electric zone.',
    avatarBg: 'from-yellow-500 to-orange-500',
    color: '#F97316',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'ANDREW',
    name: 'ANDREW',
    title: 'Armor Specialist',
    skillName: 'Armor Specialist',
    skillType: 'PASSIVE',
    description: 'Vest durability loss decreased by 20% and absorbs extra incoming bullet impact.',
    avatarBg: 'from-blue-600 to-indigo-600',
    color: '#3B82F6',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'MAXIM',
    name: 'MAXIM',
    title: 'Gluttony',
    skillName: 'Gluttony',
    skillType: 'PASSIVE',
    description: 'Eating mushrooms and using Medkits speed increased by 30%.',
    avatarBg: 'from-emerald-500 to-teal-600',
    color: '#10B981',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'PALOMA',
    name: 'PALOMA',
    title: 'Arms Dealing',
    skillName: 'Arms Dealing',
    skillType: 'PASSIVE',
    description: 'AR ammo will not take up backpack space (+120 extra AR rounds stored automatically).',
    avatarBg: 'from-purple-600 to-pink-600',
    color: '#A855F7',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'HAYATO',
    name: 'HAYATO',
    title: 'Bushido',
    skillName: 'Bushido',
    skillType: 'PASSIVE',
    description: 'The lower your max HP, the higher your armor penetration (+10% armor penetration per 20% HP missing).',
    avatarBg: 'from-red-600 to-rose-700',
    color: '#EF4444',
    unlocked: true,
    cost: 0,
  },
];

export const WEAPONS: Record<string, Weapon> = {
  AK47: {
    id: 'AK47',
    name: 'AK47',
    category: 'AR',
    damage: 38,
    headshotMultiplier: 2.5,
    fireRate: 9.5, // shots per sec
    magazineSize: 30,
    reloadTime: 2.2,
    range: 70,
    accuracy: 60,
    ammoType: 'AR',
    description: 'High damage assault rifle with powerful kick. Devastating headshot damage.',
  },
  MP40: {
    id: 'MP40',
    name: 'MP40',
    category: 'SMG',
    damage: 22,
    headshotMultiplier: 2.2,
    fireRate: 16.0,
    magazineSize: 32,
    reloadTime: 1.8,
    range: 35,
    accuracy: 75,
    ammoType: 'SMG',
    description: 'Extreme rate of fire SMG. Absolute king of close-range spray and drag-headshots.',
  },
  M1014: {
    id: 'M1014',
    name: 'M1014',
    category: 'SHOTGUN',
    damage: 94, // total pellet damage close up
    headshotMultiplier: 1.8,
    fireRate: 2.5,
    magazineSize: 6,
    reloadTime: 3.0,
    range: 15,
    accuracy: 45,
    ammoType: 'SG',
    description: 'Pump action heavy shotgun. Devastating point-blank burst.',
  },
  AWM: {
    id: 'AWM',
    name: 'AWM',
    category: 'SNIPER',
    damage: 150,
    headshotMultiplier: 2.8,
    fireRate: 0.9,
    magazineSize: 5,
    reloadTime: 3.5,
    range: 100,
    accuracy: 95,
    ammoType: 'SNIPER',
    description: 'Airdrop exclusive sniper rifle. High range and massive single shot power.',
  },
  SCAR: {
    id: 'SCAR',
    name: 'SCAR',
    category: 'AR',
    damage: 32,
    headshotMultiplier: 2.3,
    fireRate: 10.5,
    magazineSize: 30,
    reloadTime: 2.0,
    range: 65,
    accuracy: 72,
    ammoType: 'AR',
    description: 'Balanced assault rifle with low recoil and steady fire rate.',
  },
  DESERT_EAGLE: {
    id: 'DESERT_EAGLE',
    name: 'DESERT EAGLE',
    category: 'PISTOL',
    damage: 53,
    headshotMultiplier: 2.5,
    fireRate: 3.5,
    magazineSize: 7,
    reloadTime: 1.5,
    range: 45,
    accuracy: 80,
    ammoType: 'HG',
    description: 'Heavy handgun capable of impressive long-range headshot taps.',
  },
  PAN: {
    id: 'PAN',
    name: 'PAN',
    category: 'MELEE',
    damage: 65,
    headshotMultiplier: 2.0,
    fireRate: 1.5,
    magazineSize: 1,
    reloadTime: 0,
    range: 2.5,
    accuracy: 100,
    ammoType: 'NONE',
    description: 'Legendary melee pan! Blocks enemy bullets hitting your back.',
  },
};

export const WEAPON_SKINS: WeaponSkin[] = [
  {
    id: 'AK_FLAMING_DRAGON',
    weaponId: 'AK47',
    name: 'AK-47 Flaming Dragon',
    rarity: 'LEGENDARY',
    damageBonus: 2,
    rateBonus: 1,
    accuracyBonus: 0,
    color: '#EF4444',
    glowColor: '#F97316',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'MP40_POKER',
    weaponId: 'MP40',
    name: 'MP40 Royal Poker',
    rarity: 'LEGENDARY',
    damageBonus: 1,
    rateBonus: 2,
    accuracyBonus: 1,
    color: '#EAB308',
    glowColor: '#FEF08A',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'SCAR_TITAN',
    weaponId: 'SCAR',
    name: 'Ultimate Titan SCAR',
    rarity: 'EPIC',
    damageBonus: 1,
    rateBonus: 2,
    accuracyBonus: 0,
    color: '#06B6D4',
    glowColor: '#38BDF8',
    unlocked: true,
    cost: 0,
  },
];

export const GLOO_WALL_SKINS: GlooWallSkin[] = [
  {
    id: 'GLOO_CLASSIC',
    name: 'Classic Free Fire Ice',
    color: '#38BDF8',
    emblem: '❄️',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'GLOO_DRAGON',
    name: 'Red Dragon Fire Wall',
    color: '#EF4444',
    emblem: '🐉',
    unlocked: true,
    cost: 0,
  },
  {
    id: 'GLOO_BUNKER',
    name: 'Steel Bunker Shield',
    color: '#10B981',
    emblem: '🛡️',
    unlocked: false,
    cost: 1500,
  },
];
